/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.slc.sw_formato_operaciones;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import com.formdev.flatlaf.FlatLightLaf;
import com.slc.sw_formato_operaciones.DAO.EmpleadoDAO;
import com.slc.sw_formato_operaciones.DAO.LocalDAO;
import com.slc.sw_formato_operaciones.DAO.MaquinaDAO;
import com.slc.sw_formato_operaciones.DAO.OperacionDAO;
import com.slc.sw_formato_operaciones.DAO.OrdenDAO;
import com.slc.sw_formato_operaciones.entities.Empleado;
import com.slc.sw_formato_operaciones.entities.Local;
import com.slc.sw_formato_operaciones.entities.Maquina;
import com.slc.sw_formato_operaciones.entities.Operacion;
import com.slc.sw_formato_operaciones.entities.Orden;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.util.CellRangeAddress;
/**
 *
 * @author Clider Fernando Tutaya Rivera
 */
public class DobladoPanel extends javax.swing.JPanel {

    /**
     * Creates new form DobladoPanel
     */
    EmpleadoDAO empleadoDAO = new EmpleadoDAO();
    LocalDAO localDAO = new LocalDAO();
    MaquinaDAO maquinaDAO = new MaquinaDAO();
    OperacionDAO operacionDao = new OperacionDAO();
    
    DefaultTableModel defaultTableModel_Lavado = null;
    DefaultTableModel defaultTableModel_Secado = null;
    DefaultTableModel defaultTableModel_Doblado = null;
    public DobladoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_procesoDoblado = new javax.swing.JTable();
        jButton_Nuevo_procesoDoblado = new javax.swing.JButton();
        jButton_Agregar_procesoDoblado = new javax.swing.JButton();
        jButton_Eliminar_procesoDoblado = new javax.swing.JButton();
        jButton_Actualizar_procesoDoblado = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField_numOrden1_procesoDoblado = new javax.swing.JTextField();
        jTextField_cantPrendas1_procesoDoblado = new javax.swing.JTextField();
        jTextField_numOrden2_procesoDoblado = new javax.swing.JTextField();
        jTextField_cantPrendas2_procesoDoblado = new javax.swing.JTextField();
        jTextField_numOrden3_procesoDoblado = new javax.swing.JTextField();
        jTextField_cantPrendas3_procesoDoblado = new javax.swing.JTextField();
        jLabel_fecha_procesoDoblado = new javax.swing.JLabel();
        jLabel_id_procesoDoblado = new javax.swing.JLabel();
        jLabel_hora_procesoDoblado = new javax.swing.JLabel();
        jComboBox_local_procesoDoblado = new javax.swing.JComboBox<>();
        jComboBox_responsable_procesoDoblado = new javax.swing.JComboBox<>();
        jCheckBox_estado_procesoDoblado = new javax.swing.JCheckBox();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOBLADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jTable_procesoDoblado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_procesoDobladoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_procesoDoblado);

        jButton_Nuevo_procesoDoblado.setText("Nuevo");
        jButton_Nuevo_procesoDoblado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Nuevo_procesoDobladoActionPerformed(evt);
            }
        });

        jButton_Agregar_procesoDoblado.setText("Agregar");
        jButton_Agregar_procesoDoblado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Agregar_procesoDobladoActionPerformed(evt);
            }
        });

        jButton_Eliminar_procesoDoblado.setText("Eliminar");
        jButton_Eliminar_procesoDoblado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Eliminar_procesoDobladoActionPerformed(evt);
            }
        });

        jButton_Actualizar_procesoDoblado.setText("Actualizar");
        jButton_Actualizar_procesoDoblado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Actualizar_procesoDobladoActionPerformed(evt);
            }
        });

        jTextField_numOrden1_procesoDoblado.setText("jTextField1");
        jTextField_numOrden1_procesoDoblado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numOrden1_procesoDobladoActionPerformed(evt);
            }
        });

        jTextField_cantPrendas1_procesoDoblado.setText("jTextField1");

        jTextField_numOrden2_procesoDoblado.setText("jTextField1");

        jTextField_cantPrendas2_procesoDoblado.setText("jTextField1");

        jTextField_numOrden3_procesoDoblado.setText("jTextField1");
        jTextField_numOrden3_procesoDoblado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numOrden3_procesoDobladoActionPerformed(evt);
            }
        });

        jTextField_cantPrendas3_procesoDoblado.setText("jTextField1");

        jLabel_fecha_procesoDoblado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_fecha_procesoDoblado.setText("Fecha");

        jLabel_id_procesoDoblado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_id_procesoDoblado.setText("0");

        jLabel_hora_procesoDoblado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_hora_procesoDoblado.setText("Hora");

        jComboBox_local_procesoDoblado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_local_procesoDoblado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_local_procesoDobladoItemStateChanged(evt);
            }
        });

        jComboBox_responsable_procesoDoblado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox_estado_procesoDoblado.setText("Procesado");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_id_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_fecha_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_hora_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_local_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_numOrden1_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_cantPrendas1_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_numOrden2_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_cantPrendas2_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_numOrden3_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_cantPrendas3_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox_responsable_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_estado_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_numOrden1_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cantPrendas1_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_numOrden2_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cantPrendas2_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_numOrden3_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cantPrendas3_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_fecha_procesoDoblado)
                    .addComponent(jLabel_id_procesoDoblado)
                    .addComponent(jLabel_hora_procesoDoblado)
                    .addComponent(jComboBox_local_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_responsable_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_estado_procesoDoblado))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton_Nuevo_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jButton_Agregar_procesoDoblado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Eliminar_procesoDoblado)
                        .addGap(78, 78, 78)
                        .addComponent(jButton_Actualizar_procesoDoblado)
                        .addGap(56, 56, 56)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Eliminar_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Actualizar_procesoDoblado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Nuevo_procesoDoblado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Agregar_procesoDoblado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_procesoDobladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_procesoDobladoMouseClicked
        // TODO add your handling code here:
        int row = jTable_procesoDoblado.getSelectedRow();

        String row_id = jTable_procesoDoblado.getValueAt(row, 0).toString();
        String row_fecha = jTable_procesoDoblado.getValueAt(row, 1).toString();
        String row_hora = jTable_procesoDoblado.getValueAt(row, 2).toString();
        String row_local = jTable_procesoDoblado.getValueAt(row, 3).toString();
        String row_numOrden1 = jTable_procesoDoblado.getValueAt(row, 4).toString();
        String row_cantPrendas1 = jTable_procesoDoblado.getValueAt(row, 5).toString();
        String row_numOrden2 = jTable_procesoDoblado.getValueAt(row, 6).toString();
        String row_cantPrendas2 = jTable_procesoDoblado.getValueAt(row, 7).toString();
        String row_numOrden3= jTable_procesoDoblado.getValueAt(row, 8).toString();
        String row_cantPrendas3 = jTable_procesoDoblado.getValueAt(row, 9).toString();
        String row_responsable = jTable_procesoDoblado.getValueAt(row,10).toString();
        Boolean row_estado = (Boolean) jTable_procesoDoblado.getValueAt(row, 11);

        System.out.print("valor del estado" + row_estado);
        jLabel_id_procesoDoblado.setText(row_id);
        jLabel_fecha_procesoDoblado.setText(row_fecha);
        jLabel_hora_procesoDoblado.setText(row_hora);
        jComboBox_local_procesoDoblado.setSelectedItem(row_local);
        jTextField_numOrden1_procesoDoblado.setText(row_numOrden1);
        jTextField_cantPrendas1_procesoDoblado.setText(row_cantPrendas1);
        jTextField_numOrden2_procesoDoblado.setText(row_numOrden2);
        jTextField_cantPrendas2_procesoDoblado.setText(row_cantPrendas2);
        jTextField_numOrden3_procesoDoblado.setText(row_numOrden3);
        jTextField_cantPrendas3_procesoDoblado.setText(row_cantPrendas3);
        jComboBox_responsable_procesoDoblado.setSelectedItem(row_responsable);
        jCheckBox_estado_procesoDoblado.setSelected(row_estado);
    }//GEN-LAST:event_jTable_procesoDobladoMouseClicked

    private void jButton_Nuevo_procesoDobladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Nuevo_procesoDobladoActionPerformed
        // TODO add your handling code here:
        limpiarCamposTabDoblado();
        cargarTabla_TabDoblado();
    }//GEN-LAST:event_jButton_Nuevo_procesoDobladoActionPerformed

    private void jButton_Agregar_procesoDobladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Agregar_procesoDobladoActionPerformed
        // TODO add your handling code here:
        if(jTable_procesoDoblado.getSelectedRow() == -1){
            String cboLocal = jComboBox_local_procesoDoblado.getSelectedItem().toString();

            String txtOrden1 = jTextField_numOrden1_procesoDoblado.getText();
            String txtCant1 = !"".equals(jTextField_cantPrendas1_procesoDoblado.getText()) ? jTextField_cantPrendas1_procesoDoblado.getText() : "0";

            Orden orden1 = new Orden(txtOrden1,Integer.parseInt( txtCant1 ));

            String txtOrden2 = jTextField_numOrden2_procesoDoblado.getText();
            String txtCant2 = !"".equals(jTextField_cantPrendas2_procesoDoblado.getText()) ? jTextField_cantPrendas2_procesoDoblado.getText() : "0" ;

            Orden orden2 = new Orden(txtOrden2, Integer.parseInt(txtCant2));

            String txtOrden3 = jTextField_numOrden3_procesoDoblado.getText();
            String txtCant3 = !"".equals(jTextField_cantPrendas3_procesoDoblado.getText()) ? jTextField_cantPrendas3_procesoDoblado.getText() : "0" ;

            Orden orden3 = new Orden(txtOrden3, Integer.parseInt(txtCant3));

            String cboResponsable = jComboBox_responsable_procesoDoblado.getSelectedItem().toString();

            Boolean checkEstado = jCheckBox_estado_procesoDoblado.isSelected();

            //Crear objetos a partir para la superclase Operacion:
            List<Orden> listaOrdenes = new ArrayList<>();
            listaOrdenes.add(orden1);
            listaOrdenes.add(orden2);
            listaOrdenes.add(orden3);

            //Crear operacion solo si al menos hay un campo numero de Orden
            if(!txtOrden1.isEmpty() || !txtOrden1.isEmpty() || !txtOrden1.isEmpty()){
                Local local = localDAO.getLocalByName(cboLocal);

                Empleado empleado = empleadoDAO.getEmpleadoByNombresAndApellidos(cboResponsable.split(",")[0], cboResponsable.split(",")[1]);

                Operacion operacion = new Operacion("Doblado", local, listaOrdenes, null ,empleado, checkEstado);

                //Asignar la operacion con la que cada entidad se corresponde para evitar errores de persistencia
                listaOrdenes.forEach(orden -> orden.setOperacion(operacion));

                try {
                    if(operacionDao.addOperacion(operacion)){
                        JOptionPane.showMessageDialog(this, "Registro Agregado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                        cargarTabla_TabDoblado();
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo Agregar el Registro, Verifique los Datos", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (HeadlessException e) {
                    System.out.println("Error al insertar orden" + e.getMessage());
                }

                limpiarCamposTabDoblado();

            }else{
                //Mensaje de Error
                JOptionPane.showMessageDialog(this, "Ingrese al Menos un Numero de Orden!","Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
            JOptionPane.showMessageDialog(this, "El Registro ya fue Agregado", "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jButton_Agregar_procesoDobladoActionPerformed

    private void jButton_Eliminar_procesoDobladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Eliminar_procesoDobladoActionPerformed
        // TODO add your handling code here:
        int rowSelected = jTable_procesoDoblado.getSelectedRow();

        if( rowSelected >= 0 ){
            int response = JOptionPane.showConfirmDialog(this, "¿Eliminar Registro?");
            System.out.println(response);
            if(response == JOptionPane.YES_OPTION){
                Long id = Long.valueOf(jTable_procesoDoblado.getValueAt(rowSelected, 0).toString());
                try {
                    operacionDao.deleteOperacion(id);
                    limpiarCamposTabDoblado();
                    cargarTabla_TabDoblado();
                } catch (Exception e) {
                    System.out.println("Error al elminar Registro");
                }
            }else{
                System.out.println("No aceptado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un registro para eliminar", "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_Eliminar_procesoDobladoActionPerformed

    private void jButton_Actualizar_procesoDobladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Actualizar_procesoDobladoActionPerformed
        // TODO add your handling code here:
        int rowSelected = jTable_procesoDoblado.getSelectedRow();

        if( rowSelected >= 0 ){
            Operacion existOp = new OperacionDAO().getOperacionById(Long.valueOf(jTable_procesoDoblado.getValueAt(rowSelected, 0).toString()));
            // Obtener los datos de los componentes
            Long labelId = Long.valueOf(jLabel_id_procesoDoblado.getText() );
            String cboLocal = jComboBox_local_procesoDoblado.getSelectedItem().toString();
            String txtOrden1 = jTextField_numOrden1_procesoDoblado.getText();
            String txtCant1 = !"".equals(jTextField_cantPrendas1_procesoDoblado.getText()) ? jTextField_cantPrendas1_procesoDoblado.getText() : "0";
            Orden orden1 = new Orden(txtOrden1,Integer.parseInt( txtCant1 ));
            String txtOrden2 = jTextField_numOrden2_procesoDoblado.getText();
            String txtCant2 = !"".equals(jTextField_cantPrendas2_procesoDoblado.getText()) ? jTextField_cantPrendas2_procesoDoblado.getText() : "0";
            Orden orden2 = new Orden(txtOrden2, Integer.parseInt(txtCant2));
            String txtOrden3 = jTextField_numOrden3_procesoDoblado.getText();
            String txtCant3 = !"".equals(jTextField_cantPrendas3_procesoDoblado.getText()) ? jTextField_cantPrendas3_procesoDoblado.getText() : "0";
            Orden orden3 = new Orden(txtOrden3, Integer.parseInt(txtCant3));
            String cboResponsable = jComboBox_responsable_procesoDoblado.getSelectedItem().toString();
            Boolean estado = jCheckBox_estado_procesoDoblado.getModel().isSelected();

            List<Orden> listaOrdenes = new ArrayList<>();
            listaOrdenes.add(orden1);
            listaOrdenes.add(orden2);
            listaOrdenes.add(orden3);
            Local local = localDAO.getLocalByName(cboLocal);

            String nombres = cboResponsable.split(",")[0];
            String apellidos = cboResponsable.split(",")[1];
            Empleado empleado = empleadoDAO.getEmpleadoByNombresAndApellidos(nombres, apellidos);
            if(existOp != null){

                //Crear operacion
                Operacion operacion = new Operacion( labelId, "Doblado", local, listaOrdenes, null,empleado, estado);
                //Asignar la operacion con la que cada entidad se corresponde para evitar errores de persistencia
                listaOrdenes.forEach(orden -> orden.setOperacion(operacion));

                try {
                    if(operacionDao.updateOperacion(operacion) == true){
                        JOptionPane.showMessageDialog(this, "Registro Actualizado con Exito.", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                        cargarTabla_TabDoblado();
                    }else{
                        JOptionPane.showMessageDialog(this, "No se pudo Actualizar el registro, Revise los datos","Mensaje de Error", JOptionPane.ERROR_MESSAGE);

                    }

                } catch (HeadlessException e) {
                    System.out.println("Error al insertar orden" + e.getMessage());
                }
                limpiarCamposTabDoblado();
                cargarTabla_TabDoblado();

            }else{
                JOptionPane.showMessageDialog(null, "No Existe el Registro para Actualizar", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);

            }

        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un Registro para Actualizar", "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_Actualizar_procesoDobladoActionPerformed

    private void jTextField_numOrden1_procesoDobladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numOrden1_procesoDobladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numOrden1_procesoDobladoActionPerformed

    private void jTextField_numOrden3_procesoDobladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numOrden3_procesoDobladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numOrden3_procesoDobladoActionPerformed

    private void jComboBox_local_procesoDobladoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_local_procesoDobladoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_local_procesoDobladoItemStateChanged

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Llamar a los métodos en segundo plano
                limpiarCamposTabDoblado();
                cargarTabla_TabDoblado();
                return null;
            }

            @Override
            protected void done() {
                // Aquí puedes actualizar la interfaz si es necesario, una vez que los métodos terminen
                // Por ejemplo, mostrar un mensaje o actualizar algún componente visual
                System.out.println("Métodos ejecutados correctamente en segundo plano.");
            }
        };

        // Ejecutar el SwingWorker
        worker.execute();
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar_procesoDoblado;
    private javax.swing.JButton jButton_Agregar_procesoDoblado;
    private javax.swing.JButton jButton_Eliminar_procesoDoblado;
    private javax.swing.JButton jButton_Nuevo_procesoDoblado;
    private javax.swing.JCheckBox jCheckBox_estado_procesoDoblado;
    private javax.swing.JComboBox<String> jComboBox_local_procesoDoblado;
    private javax.swing.JComboBox<String> jComboBox_responsable_procesoDoblado;
    private javax.swing.JLabel jLabel_fecha_procesoDoblado;
    private javax.swing.JLabel jLabel_hora_procesoDoblado;
    private javax.swing.JLabel jLabel_id_procesoDoblado;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_procesoDoblado;
    private javax.swing.JTextField jTextField_cantPrendas1_procesoDoblado;
    private javax.swing.JTextField jTextField_cantPrendas2_procesoDoblado;
    private javax.swing.JTextField jTextField_cantPrendas3_procesoDoblado;
    private javax.swing.JTextField jTextField_numOrden1_procesoDoblado;
    private javax.swing.JTextField jTextField_numOrden2_procesoDoblado;
    private javax.swing.JTextField jTextField_numOrden3_procesoDoblado;
    // End of variables declaration//GEN-END:variables
    //Metodos para la pestaña Doblado
    
    
    private void cargarTabla_TabDoblado() {
        defaultTableModel_Doblado = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Hace que todas las celdas sean no editables
                }

                @Override
                public Class<?> getColumnClass(int columnIndex) {
                    if (columnIndex == 11) { // La columna "Estado" que tiene booleanos es la columna 12
                        return Boolean.class;
                    }
                    return super.getColumnClass(columnIndex);
                }
        };
        
        defaultTableModel_Doblado.addColumn("N°");
        defaultTableModel_Doblado.addColumn("Fecha");
        defaultTableModel_Doblado.addColumn("Hora");
        defaultTableModel_Doblado.addColumn("Local");
        defaultTableModel_Doblado.addColumn("N° Orden 1");
        defaultTableModel_Doblado.addColumn("Cant Prendas 1");
        defaultTableModel_Doblado.addColumn("N° Orden 2");
        defaultTableModel_Doblado.addColumn("Cant Prendas 2");
        defaultTableModel_Doblado.addColumn("N° Orden 3");
        defaultTableModel_Doblado.addColumn("Cant Prendas 3");
        defaultTableModel_Doblado.addColumn("Responsable");
        defaultTableModel_Doblado.addColumn("Estado");
        List<Operacion> allOperacionesDoblado = operacionDao.getOperacionesByType("Doblado");
        
        //CARGA DE OPERACIONES SECADO 
        if(!allOperacionesDoblado.isEmpty()){
             for (Operacion op : allOperacionesDoblado) {
                // Verificar que haya al menos un orden en la lista
                String numOrden1 = !op.getOrdenes().isEmpty() ? op.getOrdenes().get(0).getNumOrden() : "No encontrado";
                String cantPrendas1 = !op.getOrdenes().isEmpty() ? String.valueOf(op.getOrdenes().get(0).getCantPrendas() ): "" ;

                // Verificar que haya al menos dos órdenes en la lista
                String numOrden2 = op.getOrdenes().size() > 1 ? op.getOrdenes().get(1).getNumOrden() : "No  Encontrado";
                String cantPrendas2 = op.getOrdenes().size() > 1 ? String.valueOf(op.getOrdenes().get(1).getCantPrendas()) : "" ;

                // Verificar que haya al menos tres órdenes en la lista
                String numOrden3 = op.getOrdenes().size() > 2 ? op.getOrdenes().get(2).getNumOrden() : "No  Encontrado";
                String cantPrendas3 = op.getOrdenes().size() > 2 ? String.valueOf(op.getOrdenes().get(2).getCantPrendas()) : "";

                String responsableName = op.getResponsable() != null ? op.getResponsable().getNombres() + "," + op.getResponsable().getApellidos(): "";
                
                
                String fecha = op.getFecha() != null ? op.getFecha().toLocalDate().toString(): ""; 
                String hora = op.getFecha() != null ? op.getFecha().toLocalTime().toString(): "";
                String local = op.getLocal() != null ? op.getLocal().getNombre(): "";
                
                Boolean estado = op.getEstadoOperacion() != null ? op.getEstadoOperacion() : false;
                // Añadir fila a la tabla con datos verificados
                defaultTableModel_Doblado.addRow(
                    new Object[]{
                        op.getId().toString(),
                        fecha,
                        hora,
                        local,
                        numOrden1,
                        cantPrendas1,
                        numOrden2,
                        cantPrendas2,
                        numOrden3,
                        cantPrendas3,
                        responsableName,
                        estado
                    }
                );
            }
            
        }

        jTable_procesoDoblado.setModel(defaultTableModel_Doblado);
        jTable_procesoDoblado.getColumnModel().getColumn(0).setPreferredWidth(5);
        
        
        
    }
    
    private void limpiarCamposTabDoblado(){
        // Obtener el valor de la primera columna y la última fila
        int lastRowIndex = jTable_procesoDoblado.getRowCount() - 1;
        if (lastRowIndex >= 0) {
            Object value = jTable_procesoDoblado.getValueAt(lastRowIndex, 0);
            //Convertir a String
            String valueStr = String.valueOf(value);
            
            //Convertir a Integer e incrementar
            int valueInt = Integer.parseInt(valueStr) +  1;
            
            //Asignar al jLabel
            jLabel_id_procesoDoblado.setText(String.valueOf(valueInt));
           
        } else {
            jLabel_id_procesoDoblado.setText("0");
        }
        
        jComboBox_local_procesoDoblado.removeAllItems();
        
        
        jComboBox_responsable_procesoDoblado.removeAllItems();
        
        jTextField_numOrden1_procesoDoblado.setText("");
        jTextField_cantPrendas1_procesoDoblado.setText("");
        jTextField_numOrden2_procesoDoblado.setText("");
        jTextField_cantPrendas2_procesoDoblado.setText("");
        jTextField_numOrden3_procesoDoblado.setText("");
        jTextField_cantPrendas3_procesoDoblado.setText("");
        jCheckBox_estado_procesoDoblado.setSelected(false);
        cargarComboBoxesTabDoblado();
    }

    private void cargarComboBoxesTabDoblado(){
         List<Empleado> empleados = empleadoDAO.getAllEmpleados();
        List<Local> locales = localDAO.getAllLocales();
        
        empleados.forEach(emp -> jComboBox_responsable_procesoDoblado.addItem(emp.getNombres()+ "," + emp.getApellidos()));
        locales.forEach(local -> jComboBox_local_procesoDoblado.addItem(local.getNombre()) );
        
    }
}
